version: '2.0'
services:

  zookeeper:
    build: ../kafka
    entrypoint: ./bin/zookeeper-server-start.sh
    command:
      - config/zookeeper.properties

  kafka-0:
    build: ../kafka
    links:
      - zookeeper
    command:
      - config/server.properties
      - --override
      -   broker.id=0
      - --override
      -   advertised.listener=PLAINTEXT://kafka-0:9092

  connect-files:
    build: ../connect-files
    labels:
      com.yolean.build-target: ""
    links:
      - kafka-0

  test-connect-files-real-logs:
    build: ../connect-files
    links:
      - kafka-0
    volumes:
      - /var/log:/logs

  test-consume-files:
    image: solsson/kafkacat@sha256:1266d140c52cb39bf314b6f22b6d7a01c4c9084781bc779fdfade51214a713a8
    labels:
      com.yolean.build-contract: ""
    command:
      - -b
      - kafka-0:9092
      - -t
      - files-000
      - -C
      - -o
      - beginning
